dist: trusty
language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: 'HIGHEST_LOWEST="update"'
    - php: 7.2
    - php: 7.1
    - php: 7.0.11
    - php: 5.6
      env: 'SCENARIO=phpunit5'
    - php: 5.6
      env: 'SCENARIO=phpunit5 HIGHEST_LOWEST="update --prefer-lowest"'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - 'composer scenario "${SCENARIO}" "${HIGHEST_LOWEST-install}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
